# -*- coding: utf-8 -*-
"""krish.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZBDHujorLx3Hx5AyOsqcE4zucCqpQe7M
"""

# --- STEP 0: Setup & Silence Warnings ---
import warnings
import pandas as pd
import matplotlib.pyplot as plt
from mlxtend.frequent_patterns import apriori, association_rules
from mlxtend.preprocessing import TransactionEncoder

# This stops the Deprecation and Runtime warnings from cluttering your output
warnings.filterwarnings("ignore")

# --- 1. COLLECT DATASET ---
# Creating a transactional dataset (Simulating a grocery store)
raw_data = [['Milk', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
            ['Dill', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
            ['Milk', 'Apple', 'Kidney Beans', 'Eggs'],
            ['Milk', 'Unicorn', 'Corn', 'Kidney Beans', 'Yogurt'],
            ['Corn', 'Onion', 'Onion', 'Kidney Beans', 'Ice Cream', 'Eggs']]

print("Step 1: Dataset Collected.")

# --- 2. PREPROCESSING ---
# Transforming list of lists into a One-Hot Encoded format
te = TransactionEncoder()
te_ary = te.fit(raw_data).transform(raw_data)
df = pd.DataFrame(te_ary, columns=te.columns_)

print("Step 2: Preprocessing Complete (One-Hot Encoding).")

# --- 3. FEATURE EXTRACTION ---
# We extract 'Frequent Itemsets' that appear in at least 60% of transactions
frequent_itemsets = apriori(df, min_support=0.6, use_colnames=True)

print("Step 3: Feature Extraction Complete (Frequent Itemsets identified).")

# --- 4. TRAINING ---
# Training the model to find associations using the 'lift' metric
# Lift > 1 indicates a strong relationship between items
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1.0)

print("Step 4: Model Training Complete.")

# --- 5. TESTING ---
# We refine the rules and format them for readability
# We test the strength of the rules by sorting by Confidence
final_rules = rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']].copy()
final_rules['antecedents'] = final_rules['antecedents'].apply(lambda x: ', '.join(list(x)))
final_rules['consequents'] = final_rules['consequents'].apply(lambda x: ', '.join(list(x)))

print("Step 5: Testing & Rule Refinement Complete.")

# --- 6. EVALUATION ---
# Displaying the final results and a visualization
print("\n--- STEP 6: FINAL EVALUATION RESULTS ---")
display(final_rules.sort_values(by='lift', ascending=False))

# Visual Evaluation Plot
plt.figure(figsize=(10, 4))
plt.scatter(rules['support'], rules['confidence'], c=rules['lift'], cmap='viridis', s=100)
plt.title('Evaluation: Support vs Confidence (Colored by Lift)')
plt.xlabel('Support')
plt.ylabel('Confidence')
plt.colorbar(label='Lift Strength')
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()

